#!/usr/bin/sh
## Used to show how much network I have used, so when I am on a hotspot I dont go too mental

awk '/wlo1/ {down=$2/1000000; up=$10/1000000; printf "%1d Mib\n",up+down}' /proc/net/dev
#%1d is no decimal points
#%0.1f is one decimal point
